name: Send Silent Push Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  send-silent-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq python3-pip
          pip3 install --user google-auth

      - name: Generate Access Token
        id: token
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > sa.json
          ACCESS_TOKEN=$(python3 - <<EOF
import json
import google.oauth2.service_account
import google.auth.transport.requests

with open("sa.json") as f:
    sa_info = json.load(f)

credentials = google.oauth2.service_account.Credentials.from_service_account_info(
    sa_info, scopes=["https://www.googleapis.com/auth/firebase.messaging"]
)
request = google.auth.transport.requests.Request()
credentials.refresh(request)
print(credentials.token)
EOF
)
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

      - name: Send Silent Push
        env:
          FCM_TOKEN: ${{ secrets.DEVICE_FCM_TOKEN }}
          PROJECT_ID: lite-360
          ACCESS_TOKEN: ${{ steps.token.outputs.access_token }}
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            https://fcm.googleapis.com/v1/projects/$PROJECT_ID/messages:send \
            -d '{
              "message": {
                "token": "'"$FCM_TOKEN"'",
                "apns": {
                  "headers": { "apns-priority": "10" },
                  "payload": { "aps": { "content-available": 1 } }
                },
                "data": {
                  "silent": "true",
                  "action": "location_upload"
                }
              }
            }'
