name: Send Silent Push

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests google-auth

    - name: Run push script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS" > service-account.json
        python send_push.py
