name: Send Push Notification

on:
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes (this can be adjusted)
  workflow_dispatch:  # allows you to manually trigger the workflow

jobs:
  send_notification:
    runs-on: ubuntu-latest   # runs on a Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   # makes sure your code is available in the runner

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'   # specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-auth   # install dependencies

      - name: Run the Python script
        run: |
          python send_push.py   # runs your Python script

